title: "The Lainey Log"
email: laineypaulus@gmail.com
description: "My blog where I'll discuss my travels during my semester abroad."
baseurl: "" 
url: "https://laineyp-blog.github.io"

theme: minima
